# Array Functions

In [1]:
import numpy as np

In [2]:
#have both int and float but for output it will convert all of them into float
a=np.array([10,2,100,0.3,2,1.5])
a

array([ 10. ,   2. , 100. ,   0.3,   2. ,   1.5])

In [3]:
a.sort()
a

array([  0.3,   1.5,   2. ,   2. ,  10. , 100. ])

In [4]:
b=np.array([12,3,71,2.8,22,9.9])

In [5]:
c=np.concatenate((a,b))
c

array([  0.3,   1.5,   2. ,   2. ,  10. , 100. ,  12. ,   3. ,  71. ,
         2.8,  22. ,   9.9])

In [6]:
c.sort()
c

array([  0.3,   1.5,   2. ,   2. ,   2.8,   3. ,   9.9,  10. ,  12. ,
        22. ,  71. , 100. ])

2D Array

In [7]:
a=np.array([[1,2,3],[6,7,8]])
a

array([[1, 2, 3],
       [6, 7, 8]])

In [8]:
b=np.array([[3,2,1],[1,2,3]])
b

array([[3, 2, 1],
       [1, 2, 3]])

In [9]:
c=np.concatenate((a,b),axis=0)
c

array([[1, 2, 3],
       [6, 7, 8],
       [3, 2, 1],
       [1, 2, 3]])

In [10]:
c=np.concatenate((a,b),axis=1)
c

array([[1, 2, 3, 3, 2, 1],
       [6, 7, 8, 1, 2, 3]])

In [11]:
d=np.array([[[1,2,3],
            [2,1,1]],
           [[2,3,4],
           [5,6,7]],
           [[8,4,5],
            [3,6,0]]]
)
d

array([[[1, 2, 3],
        [2, 1, 1]],

       [[2, 3, 4],
        [5, 6, 7]],

       [[8, 4, 5],
        [3, 6, 0]]])

In [12]:
#to find dimensin
d.ndim

3

In [13]:
#number of elements(in size)
d.size

18

In [14]:
#shape(proper like 3 array,then on y axis (|)2 elements in col and 3 on x axis(_))
d.shape

(3, 2, 3)

In [15]:
#reshape(in col wise)
np.reshape(a,newshape=(1,6),order='C')

array([[1, 2, 3, 6, 7, 8]])

In [16]:
#convert 1d into 2d
a=np.array([1,2,3,4])
a.shape

(4,)

In [17]:
#row wise
b=a[np.newaxis,:]
b

array([[1, 2, 3, 4]])

In [18]:
b.shape

(1, 4)

In [19]:
#col wise
c=a[:,np.newaxis]
c

array([[1],
       [2],
       [3],
       [4]])

In [20]:
a.sum()

10

In [21]:
a*2

array([2, 4, 6, 8])

In [22]:
a+3

array([4, 5, 6, 7])