# numpy 1D

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
print(a)

[1 2 3]


In [4]:
type(a)

numpy.ndarray

In [5]:
len(a)

3

In [6]:
#to access number 
a[0]
a[2]

3

In [7]:
#to access all numbers 0 till end
a[0:]

array([1, 2, 3])

In [8]:
c=np.zeros(3)
d=np.ones(3)
print(d)
print(c)

[1. 1. 1.]
[0. 0. 0.]


In [9]:
#with range of elements
f=np.arange(6)
f

array([0, 1, 2, 3, 4, 5])

In [10]:
#with specific number of range
f=np.arange(2,20)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [11]:
#continue(means go to 2 till 19 but with a gap of 2 )
f=np.arange(2,20,2)
f

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
#linerly spaced array(means fom 0 to 20 and total 5 num & the nums are in such a way that they have same addition value in ur case its 5)
g=np.linspace(0,20,num=5)
g

array([ 0.,  5., 10., 15., 20.])

In [13]:
#specific datatypes in array
g=np.ones(5,dtype=np.int8)
g

array([1, 1, 1, 1, 1], dtype=int8)