# Numpy 2D

In [2]:
import numpy as np

In [3]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
type(b)

numpy.ndarray

In [5]:
#length of a matrix
len(b)

3

In [6]:
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
#if want row
b[0]

array([1, 2, 3])

In [8]:
#if want whole matrix
b[0:] #means 0 till end

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [11]:
np.empty((3,3))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [6.23043429e-307, 2.22526399e-307, 6.23053614e-307],
       [7.56592338e-307, 9.34588061e-307, 3.62651150e-317]])

### 3D

In [20]:
#creation of 3d array(add amount of numbers in arange like we could have total of 18 in our these 2 arrays so we write 18 if it has 24 so it could be (2,3,4)
a=np.arange(18).reshape(2,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])